### ISSUE TITLE
HistoryRenderer crashes instantly if you have completed less then 12 solves

### ISSUE THREAD

**Issue by terukaaz** [Chromatic-Vision/cubescramble-rewrite#2]
Traceback (most recent call last):
  File "C:\Users\terukaaz\PycharmProjects\cubescramble-rewrite\main.py", line 22, in <module>
    game.update(events)
  File "C:\Users\terukaaz\PycharmProjects\cubescramble-rewrite\game.py", line 136, in update
    self.history_renderer.re_render()
  File "C:\Users\terukaaz\PycharmProjects\cubescramble-rewrite\renderer\history.py", line 77, in re_render
    self.draw_graph(self.s,
  File "C:\Users\terukaaz\PycharmProjects\cubescramble-rewrite\renderer\history.py", line 96, in draw_graph
    longest = max(max(time for time in graph_stat.data if time is not None) for graph_stat in stats)
  File "C:\Users\terukaaz\PycharmProjects\cubescramble-rewrite\renderer\history.py", line 96, in <genexpr>
    longest = max(max(time for time in graph_stat.data if time is not None) for graph_stat in stats)
ValueError: max() arg is an empty sequence

Process finished with exit code 1

**Comment by terukaaz** [comment]
It has been fixed, but it crashes now if you open up the graph whenever no single solve is completed. Closing this issue assuming nobody opens the graph in that circumstances.
